const dotenv = require('dotenv');

dotenv.config();

const FILE_UPLOADER_GDRIVE_TEAMDRIVE = (
  process.env.FILE_UPLOADER_GDRIVE_TEAMDRIVE || ''
).trim();

const FILE_UPLOADER_GDRIVE_CLIENT_EMAIL =
  process.env.FILE_UPLOADER_GDRIVE_CLIENT_EMAIL;

const FILE_UPLOADER_GDRIVE_PRIVATE_KEY =
  process.env.FILE_UPLOADER_GDRIVE_PRIVATE_KEY;

// must be multiples of 256Kb
const FILE_UPLOADER_GDRIVE_CHUNKS =
  process.env.FILE_UPLOADER_GDRIVE_CHUNKS || 100;

module.exports = {
  FILE_UPLOADER_GDRIVE_TEAMDRIVE,
  FILE_UPLOADER_GDRIVE_CLIENT_EMAIL,
  FILE_UPLOADER_GDRIVE_PRIVATE_KEY,
  FILE_UPLOADER_GDRIVE_CHUNKS,
};
